# Site settings
title: My deskbound life
email: brian@3snip.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/mydeskboundlife/" # the subpath of your site, e.g. /blog/
url: "http://butchpeters.github.io" # the base hostname & protocol for your site
twitter_username: butch_peters
github_username:  butchpeters

# Build settings
markdown: kramdown
