# Site settings
title: My deskbound life
email: brian@3snip.com
description: >
  "My deskbound life" chronicles my ongoing story of maintaining a healthy lifestyle
  while bound to a desk for 8 hours a day. 
baseurl: "/mydeskboundlife/" # the subpath of your site, e.g. /blog/
url: "http://butchpeters.github.io" # the base hostname & protocol for your site
twitter_username: butch_peters
github_username:  butchpeters

# Build settings
markdown: kramdown
